### ISSUE TITLE
'graph' type

### ISSUE THREAD

**Issue by gcrois** [cadebrown/kscript#3]
This type will have basic graph functionality: nodes can have edges which lead to other nodes. There is no differentiation between directed and undirected graphs. Ensure traversal and rearranging is easily accomplished and well-documented.

In the future, we may include type functions for various graph algorithms or graph states (Hamiltonian?, Dijkstra's, A*, Network Flow, etc.)

**Comment by cadebrown** [comment]
This issue is addressed in #9
